In [81]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [20]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?campaign=homepage_explore_companies_widget&page=1',headers=headers).text

In [21]:
soup = BeautifulSoup(webpage,'lxml')

In [ ]:
print(soup.prettify())

In [ ]:
raw_text = soup.find_all('h1')[0].text 
clean_text = " ".join(raw_text.split())
clean_text

'Top Companies in INDIA'

In [ ]:
soup.find_all('h2')

In [ ]:
for i in soup.find_all('h2'):
    print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Jio
Axis Bank
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTIMindtree
HDB Financial Services
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [42]:
raw_text1= soup.find_all('div', class_="rating_text rating_text--md")[0].text

clean_text1 = " ".join(raw_text1.split())
clean_text1

'3.3'

In [ ]:
for i in soup.find_all('div', class_="rating_text rating_text--md"):
    print(i.text.strip())

In [ ]:
for i in soup.find_all('span',class_='companyCardWrapper__companyRatingCount'):
    print(i.text.strip())

In [ ]:
for i in soup.find_all('span', class_="companyCardWrapper__ratingValues"):
    print(i.text.strip())

In [ ]:
for i in soup.find_all('span', class_="companyCardWrapper__ratingValues"):
    print(i.text.strip())

In [53]:
company = soup.find_all('div',class_= 'companyCardWrapper')
len(company)

20

In [ ]:
name =[]
rating= []
Reviews = []
Salaries = []
Interviews=[]
Jobs =[]
Benefits=[]
Highly_Rated_for = []
Critically_Rated_for = []
for i in company:
    name.append((i.find('h2').text.strip()))
    rating.append(i.find('div', class_='rating_text rating_text--md').text.strip())
    Reviews.append(i.find_all('span','companyCardWrapper__ActionCount')[0].text.strip())
    Salaries.append(i.find_all('span','companyCardWrapper__ActionCount')[1].text.strip())
    Interviews.append(i.find_all('span','companyCardWrapper__ActionCount')[2].text.strip())
    Jobs.append(i.find_all('span','companyCardWrapper__ActionCount')[3].text.strip())
    Benefits.append(i.find_all('span','companyCardWrapper__ActionCount')[4].text.strip())
    try:
        Highly_Rated_for.append(i.find_all('span', class_="companyCardWrapper__ratingValues")[0].text.strip())
    except:
        Highly_Rated_for.append(np.nan) 
    try:
        Critically_Rated_for.append(i.find_all('span', class_="companyCardWrapper__ratingValues")[1].text.strip())
    except:
        Critically_Rated_for.append(np.nan)


d = {'name':name ,'Rating':rating,'Reviews' :Reviews ,'Salaries':Salaries,'Interviews':Interviews,'Jobs':Jobs,'Benefits':Benefits,'Highly_Rated_for':Highly_Rated_for ,'Critically_Rated_for':Critically_Rated_for}

df = pd.DataFrame(d)
df

In [ ]:
final = pd.DataFrame()
for j in range(1,7):
    
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage = requests.get('https://www.ambitionbox.com/list-of-companies?campaign=homepage_explore_companies_widget&page={}'.format(j),headers=headers).text
    soup = BeautifulSoup(webpage,'lxml')
    company = soup.find_all('div',class_= 'companyCardWrapper')
    name =[]
    rating= []
    Reviews = []
    Salaries = []
    Interviews=[]
    Jobs =[]
    Benefits=[]
    Highly_Rated_for = []
    Critically_Rated_for = []
    for i in company:
        name.append((i.find('h2').text.strip()))
        rating.append(i.find('div', class_='rating_text rating_text--md').text.strip())
        Reviews.append(i.find_all('span','companyCardWrapper__ActionCount')[0].text.strip())
        Salaries.append(i.find_all('span','companyCardWrapper__ActionCount')[1].text.strip())
        Interviews.append(i.find_all('span','companyCardWrapper__ActionCount')[2].text.strip())
        Jobs.append(i.find_all('span','companyCardWrapper__ActionCount')[3].text.strip())
        Benefits.append(i.find_all('span','companyCardWrapper__ActionCount')[4].text.strip())
        try:
            Highly_Rated_for.append(i.find_all('span', class_="companyCardWrapper__ratingValues")[0].text.strip())
        except:
            Highly_Rated_for.append(np.nan) 
        try:
            Critically_Rated_for.append(i.find_all('span', class_="companyCardWrapper__ratingValues")[1].text.strip())
        except:
            Critically_Rated_for.append(np.nan)


    d = {'Name':name ,'Rating':rating,'Reviews' :Reviews ,'Salaries':Salaries,'Interviews':Interviews,'Jobs':Jobs,'Benefits':Benefits,'Highly_Rated_for':Highly_Rated_for ,'Critically_Rated_for':Critically_Rated_for}

    df = pd.DataFrame(d)
    
    final = pd.concat([final, df], ignore_index=True)


final

,Name,Rating,Reviews,Salaries,Interviews,Jobs,Benefits,Highly_Rated_for,Critically_Rated_for
0,TCS,3.3,1.2L,10.2L,11.4k,4.6k,10.8k,Job Security,"Promotions, Salary, Work Satisfaction"
1,Accenture,3.7,74.4k,7.1L,9.4k,30.3k,6.8k,"Promotions, Salary, Work Satisfaction",NaN
2,Wipro,3.6,65.8k,4.9L,6.9k,329,4.8k,"Promotions, Salary, Work Satisfaction",NaN
3,Cognizant,3.7,62.1k,6.1L,6.5k,775,5.6k,"Promotions, Salary, Work Satisfaction",NaN
4,Capgemini,3.6,54.1k,4.9L,5.6k,2.3k,3.8k,"Work Life Balance, Job Security","Promotions, Salary, Work Satisfaction"
...,...,...,...,...,...,...,...,...,...
115,Standard Chartered,3.6,5.8k,42.5k,331,1,318,"Promotions, Work Satisfaction, Salary",NaN
116,Apollo Hospitals,4.0,5.7k,16.9k,499,286,525,"Job Security, Skill Development, Company Culture",Promotions
117,Mahindra Finance,3.9,5.7k,12.4k,227,127,526,Promotions,NaN
118,Udaan,3.9,5.7k,14.8k,376,--,762,Salary,"Job Security, Promotions"
119,Swiggy,3.7,5.7k,24.5k,598,198,369,"Job Security, Promotions, Work Life Balance",NaN

In [113]:
final

,Name,Rating,Reviews,Salaries,Interviews,Jobs,Benefits,Highly_Rated_for,Critically_Rated_for
0,TCS,3.3,1.2L,10.2L,11.4k,4.6k,10.8k,Job Security,"Promotions, Salary, Work Satisfaction"
1,Accenture,3.7,74.4k,7.1L,9.4k,30.3k,6.8k,"Promotions, Salary, Work Satisfaction",NaN
2,Wipro,3.6,65.8k,4.9L,6.9k,331,4.8k,"Promotions, Salary, Work Satisfaction",NaN
3,Cognizant,3.7,62.1k,6.1L,6.5k,780,5.6k,"Promotions, Salary, Work Satisfaction",NaN
4,Capgemini,3.6,54.1k,4.9L,5.6k,2.3k,3.8k,"Work Life Balance, Job Security","Promotions, Salary, Work Satisfaction"
...,...,...,...,...,...,...,...,...,...
115,Standard Chartered,3.6,5.8k,42.5k,331,1,318,"Promotions, Work Satisfaction, Salary",NaN
116,Apollo Hospitals,4.0,5.7k,16.9k,499,286,525,"Job Security, Skill Development, Company Culture",Promotions
117,Mahindra Finance,3.9,5.7k,12.4k,227,127,526,Promotions,NaN
118,Udaan,3.9,5.7k,14.8k,376,--,762,Salary,"Job Security, Promotions"
119,Swiggy,3.7,5.7k,24.5k,598,198,369,"Job Security, Promotions, Work Life Balance",NaN

In [99]:
final.shape

(121, 9)

In [86]:
Critically_Rated_for

['Promotions, Salary, Work Satisfaction',
 nan,
 nan,
 nan,
 'Promotions, Salary, Work Satisfaction',
 'Promotions, Salary',
 'Promotions, Salary, Work Satisfaction',
 nan,
 nan,
 nan,
 'Promotions, Salary, Work Satisfaction',
 nan,
 nan,
 nan,
 'Promotions, Salary, Work Satisfaction',
 'Promotions',
 'Promotions',
 nan,
 nan,
 'Promotions, Salary']